import Head from 'next/head'
import Navbar from './components/Navbar'
import Recentpost from './components/Recentpost'
import FeaturedWork from './components/FeaturedWork'
import Profile from './components/Profile'
import Footer from './components/Footer'
import { ProfileController } from './controller/profile'
import { FooterController } from './controller/footer'
import { WorkController } from './controller/work'
import { BlogController } from './controller/blog'
import { homeViewInterface } from './config/interface'

export default function Home(prop:homeViewInterface) {

  return (
    <div>
      <Head>
        <title>johedotcom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Navbar/>
      <Profile {...prop.profile}/>

      <Recentpost blog={prop.blog}/>
      <FeaturedWork work={prop.work} title={`Featured Works`}/>
      <Footer footers={prop.footer}/>
    </div>
  )
}

export async function getServerSideProps() {
  
  const profileData = await ProfileController.GetProfile()
  const footerData = await FooterController.GetFooter()
  const workData = await WorkController.GetWorkByDate()
  const blogData = await BlogController.GetBlogByDate()

  return {props:{
    profile:profileData,
    footer:footerData,
    work:workData,
    blog:blogData
  }}
}