import Head from 'next/head'
import Navbar from './components/Navbar'
import Recentpost from './components/Recentpost'
import FeaturedWork from './components/FeaturedWork'
import Profile from './components/Profile'
import { homeInterface } from './config/interface'
import Footer from './components/Footer'
import { ProfileController } from './controller/profile'
import { FooterController } from './controller/footer'

export default function Home(prop:homeInterface) {

  return (
    <div>
      <Head>
        <title>johedotcom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <Navbar/>

      <Profile {...prop.profile}/>
      <Recentpost/>
      <FeaturedWork title={`Featured Works`}/>
      
      <Footer footers={prop.footer}/>
    </div>
  )
}

export async function getServerSideProps() {
  
  const profileData = await ProfileController.GetProfile()
  const footerData = await FooterController.GetFooter()

  return {props:{
    profile:profileData,
    footer:footerData
  }}
}