import Head from 'next/head'
import { FeaturedWork } from './components/FeaturedWork'
import { Footer } from './components/Footer'
import { Navbar } from './components/Navbar'
import { Profile } from './components/Profile'
import { Recentpost } from './components/Recentpost'
import { doc, getDoc } from 'firebase/firestore/lite'
import { db, storage } from './config/firebase'
import { homeInterface, profileInterface } from './config/interface'
import { getDownloadURL, ref } from 'firebase/storage'



export default function Home(prop:homeInterface) {

  console.log(prop)

  return (
    <div>
      <Head>
        <title>johedotcom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <Navbar/>

      <Profile {...prop.profile}/>
      <Recentpost/>
      <FeaturedWork title={`Featured Works`}/>
      
      <Footer/>
    </div>
  )
}

export async function getServerSideProps() {
  const docRef = doc(db, 'profile', 'johe')
  const profileData = (await getDoc(docRef)).data() as profileInterface
  
  const imageRef = ref(storage, `profile/${profileData.picture}`)
  profileData.picture = await getDownloadURL(imageRef)
  
  return {props:{
    profile:profileData
  }}
}